name: PR

on:
  pull_request:
    branches:
      - "iss*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Check format
        run: npm run format:check
        working-directory: ./frontend

      - name: Check lint
        run: npm run lint
        working-directory: ./frontend
